<?php


$play = 'CREATE TABLE `challenge16`.`temp` (
`coverImg` VARCHAR(255) UNSIGNED NOT NULL ,
`mainPageTitle` VARCHAR(255) UNSIGNED NOT NULL ,
`subtitleOfPage` VARCHAR(255) UNSIGNED NOT NULL ,
`about` TEXT UNSIGNED NOT NULL ,
`telNumber` VARCHAR(255) UNSIGNED NOT NULL ,
`Location` VARCHAR(255) UNSIGNED NOT NULL ,
`servicesOrProducts` VARCHAR(255) UNSIGNED NOT NULL ,
`imgUrl1` VARCHAR(255) UNSIGNED NOT NULL ,
`descService1` VARCHAR(255) UNSIGNED NOT NULL ,
`imgUrl2` VARCHAR(255) UNSIGNED NOT NULL ,
`descService2` VARCHAR(255) UNSIGNED NOT NULL ,
`imgUrl2` VARCHAR(255) UNSIGNED NOT NULL ,
`descService2` VARCHAR(255) UNSIGNED NOT NULL ,
`imgUrl3` VARCHAR(255) UNSIGNED NOT NULL ,
`descService3` VARCHAR(255) UNSIGNED NOT NULL ,
`linkedin` TEXT UNSIGNED NOT NULL ,
`facebook` VARCHAR(255) UNSIGNED NOT NULL ,
`twitter` VARCHAR(255) UNSIGNED NOT NULL ,
`instagram` VARCHAR(255) UNSIGNED NOT NULL ,
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT ,
PRIMARY KEY (`id`)
)
 ENGINE = InnoDB;';
